### ISSUE TITLE
moveWidgetChild causes the item on widget to disappear when a negative number is used for the Y axis offset

### ISSUE THREAD

**Issue by DennisMartinez** [rune-js/server#184]
Calling `moveWidgetChild` with a negative offset on the Y axis looks to be making the item on the widget disappear.

Here's a sample plugin which uses [itemSelectionAction](https://github.com/rune-js/server/blob/master/src/world/actor/player/action/item-selection-action.ts#L53) to ask the user for input, which calls [moveWidgetChild](https://github.com/rune-js/server/blob/master/src/world/actor/player/action/item-selection-action.ts#L81) internally.

```typescript
import { itemOnItemAction } from '@server/world/actor/player/action/item-on-item-action';
import { itemSelectionAction } from '@server/world/actor/player/action/item-selection-action';
import { RunePlugin, ActionType } from '@server/plugins/plugin';

const action: itemOnItemAction = ({ player }) => {
    itemSelectionAction(player, 'COOKING', [
        { itemId: 377, itemName: 'Raw Lobster', offset: -12 }
    ]);
};

export default new RunePlugin([
    {
        type: ActionType.ITEM_ON_ITEM_ACTION,
        items: [{ item1: 377, item2: 377 }],
        action
    }
]);
```

Change `offset: -12` to a positive number and the item reappears.

You can use raw lobster on another raw lobster to bring up the interface in the sample plugin. `::item 377 2`

**Comment by TheBlackParade** [comment]
<img width="411" alt="Screen Shot 2020-06-28 at 9 21 56 PM" src="https://user-images.githubusercontent.com/58998065/85966442-684eb900-b985-11ea-88e7-dcc9d2647fe1.png">

Think I got it fixed. Made a mistake in the client. 😅

**Comment by TheBlackParade** [comment]
Closing this as I've merged the fix into the client's master branch
