### ISSUE TITLE
Private, group, and global world instances

### ISSUE THREAD

**Issue by TheBlackParade** [rune-js/server#206]
* Players should be able to have their own private game instance, including their own personal game objects, NPCs, and world items.
  * Players should not be able to see actions of other players in their private instance.
  * Other players should not be able to see the actions of this player in their private instance.
* Players should be able to join a group instance where they share the aforementioned resources - game objects, NPCs, and world items.
  * Players outside of this group instance should not be able to see the actions of those within.
  * Vise versa for those inside in instance.
* The game world should have a global instance that applies to all players and NPCs that are not assigned to a specific instance (they are not in private gameplay of any kind).
  * This is a game instance shared by everyone within the world that is not in a private instance. 
  * All world items, objects, NPCsc, etc are visible to everyone inside the global instance.
* The global instance and private instances can not be engaged at the same time. The player must be either in the global instance or a specific instance - whether that be a group or private instance.
* Friends list status is independent of instances - a player is shown as online regardless of which instance type they are logged into.

**Comment by Tynarus** [comment]
Completed by #220
