### ISSUE TITLE
In the skill guide widget, you can't view more than two sub menus

### ISSUE THREAD

**Issue by SchauweM** [rune-js/server#251]
When opening a skill guide, you're able to view the first menu of items. Clicking on a second menu item such as "Bows" on the "Fletching" skill guide will result in the replacement of title for that child id to "Please wait" (`English.pleaseWait` in the client). The widget will open said sub menu but the widget will be stuck from there on until you close it.

![image](https://user-images.githubusercontent.com/7024705/109435031-89860e80-7a18-11eb-8656-7ab366dab7ba.png)

I've already done some debugging and it appears that the client gets stuck on `Main.java:236 in the client`. Other functions won't get called from `skill-guide-plugin.ts`.

**Comment by Tynarus** [comment]
Fixed by #253
