### ISSUE TITLE
[BUG] Chatbox interfaces

### ISSUE THREAD

**Issue by Gallus-RSPS** [rune-js/server#318]
After your recent push, I am still experiencing the chatbox interface issue where "Click to continue" just makes server give  "Please wait..." indefinitely.

**Comment by src52** [comment]
When you say Click to Continue, you mean when going through a dialogue, correct? If so, which dialogue are you experiencing this issue with?

**Comment by SchauweM** [comment]
@Tynarus this is regarding your recent push on #01135bd

**Comment by Gallus-RSPS** [comment]
Skill level up interface

**Comment by Jameskmonger** [comment]
can confirm this is still an issue
