### ISSUE TITLE
[BUG] Coins are not removed from inventory when 0

### ISSUE THREAD

**Issue by hallowatcher** [rune-js/server#331]
**Describe the bug**
When spending all coins in your inventory, it should be checked if you have 0. If so, remove the item.

**To Reproduce**
1. Grab the coins next to the Lumbridge general store
2. Buy some stuff
3. 0 coins are shown in the inventory

**Expected behavior**
Coins are removed from the inventory

**Screenshots**
![image](https://user-images.githubusercontent.com/6265839/123159250-15f78980-d46d-11eb-89cb-db54b681d4ca.png)

**Comment by SchauweM** [comment]
@hallowatcher is this item specific or does this count for every stackable item?

**Comment by hallowatcher** [comment]
Good question, I don't know what else deducts from a stackable item other than arrows when using ranged maybe? I know this works when banking notes

**Comment by SchauweM** [comment]
Runes, arrows, noted items, purple sweets, seeds, feathers, arrow shafts, nails, bolt tips

**Comment by src52** [comment]
We can add a check in the inventory/bank's add method that ensures the item being added isn't 0. I experienced this same bug today.

**Comment by SchauweM** [comment]
> We can add a check in the inventory/bank's add method that ensures the item being added isn't 0. I experienced this same bug today.

Does it actually add 0 of an item? Just wondering since I havn't looked at it yet. But yes this should be added either way. Feel free to create a PR if you think you've got time!

**Comment by src52** [comment]
> > We can add a check in the inventory/bank's add method that ensures the item being added isn't 0. I experienced this same bug today.
> 
> Does it actually add 0 of an item? Just wondering since I havn't looked at it yet. But yes this should be added either way. Feel free to create a PR if you think you've got time!

![image](https://user-images.githubusercontent.com/17970489/127699463-7605666b-ec2b-4873-afaf-6908de31e2ee.png)
Yep! The player's save lists it as being a zero amount as well.

**Comment by SchauweM** [comment]
> > > We can add a check in the inventory/bank's add method that ensures the item being added isn't 0. I experienced this same bug today.
> > 
> > 
> > Does it actually add 0 of an item? Just wondering since I havn't looked at it yet. But yes this should be added either way. Feel free to create a PR if you think you've got time!
> 
> ![image](https://user-images.githubusercontent.com/17970489/127699463-7605666b-ec2b-4873-afaf-6908de31e2ee.png)
> Yep! The player's save lists it as being a zero amount as well.

Thank you for debugging!

Do you think You'll be able to make a PR with a fix? If not, I'll commit to it next week when I get back.

**Comment by src52** [comment]
> > > > We can add a check in the inventory/bank's add method that ensures the item being added isn't 0. I experienced this same bug today.
> > > 
> > > 
> > > Does it actually add 0 of an item? Just wondering since I havn't looked at it yet. But yes this should be added either way. Feel free to create a PR if you think you've got time!
> > 
> > 
> >https://user-images.githubusercontent.com/17970489/127699463-7605666b-ec2b-4873-afaf-6908de31e2ee.png
> > Yep! The player's save lists it as being a zero amount as well.
> 
> Thank you for debugging!
> 
> Do you think You'll be able to make a PR with a fix? If not, I'll commit to it next week when I get back.

No worries at all, and yes. It's already fixed on my end. I can definitely make a PR. 👍

**Comment by SchauweM** [comment]
@src52 any news on the PR? If not you can supply the code on the discord or here and I'll add it myself. No need to do double the work 😅

**Comment by SchauweM** [comment]
There is an issue with the cache values as they might be missing. We'll be putting this issue on the back burner until @Tynarus has finished up the filestore revamp.

**Comment by src52** [comment]
> @src52 any news on the PR? If not you can supply the code on the discord or here and I'll add it myself. No need to do double the work 😅

This should solve the issue, I believe. #340 checks that the item being added doesn't have a quantity of zero.
