### ISSUE TITLE
[BUG] Weird behaviour when buying from shops

### ISSUE THREAD

**Issue by hallowatcher** [rune-js/server#332]
**Describe the bug**
When you spend your coins in a shop, the prices shown are not the actual prices you spend

**To Reproduce**
See this video: https://hwc.hr/i/wXx8n63b.mp4

**Expected behavior**
When checking the "Value" of items, I expect to spend that amount of coins.

**Comment by Tynarus** [comment]
Dang, that's pretty messed up haha. Thanks for the video recreation!

**Comment by SchauweM** [comment]
There is an issue with the cache values as they might be missing. We'll be putting this issue on the back burner until @Tynarus has finished up the filestore revamp.
