### ISSUE TITLE
[BUG] Withdrawing large quantities of stacked items from the bank causes the server to crash.

### ISSUE THREAD

**Issue by src52** [rune-js/server#336]
**Describe the bug**
When stacked items are withdrawn from the player's bank, a for-loop adds the items to the player's inventory one-by-one. When each new item of the stack is added, the container is updated with `this._containerUpdated.next()` causing the server to crash if withdrawing large quantities of items due to the large amount of refresh calls.

**To Reproduce**
1. Open the bank.
2. Withdraw a large amount of stacked items.
3. The server becomes unresponsive, (especially if you have items in your inventory that aren't registered with the server. Console gets flooded with item warning messages.)

**Expected behavior**
A single inventory add/change, instead of X amount of changes for stacked items.

**Solution**
In bank.plugin.ts:173, remove the for-loop and change `playerInventory.add({ itemId: itemIdToAdd, amount: 1 });` to `playerInventory.add({ itemId: itemIdToAdd, amount: countToRemove });`

**Comment by SchauweM** [comment]
Thanks for reporting this bug @src52! Feel free to make a PR with your proposed solution if you havn't already.

If not, we'll try to apply a fix with your suggested solution ASAP.
