### ISSUE TITLE
[BUG] Withdrawing stacked non stackables from bank

### ISSUE THREAD

**Issue by RedSparr0w** [rune-js/server#353]
**Describe the bug**
When withdrawing multiple items that are not stackable, they will withdraw as stacks

**To Reproduce**
1. Open the bank
2. Withdraw more than 1 of any non-stackable item
3. Items withdrawn as stacks

**Expected behavior**
Individual items withdrawn until inventory full or total number of items attempted to withdraw are withdrawn

**Comment by SchauweM** [comment]
Thanks for reporting the bug!

Upon further investigation, it seems that only the option `Withdrawn-1 {item}` is not affected and works as intended. All other options stack non-stackable items.
