### ISSUE TITLE
Build issue, rimraf not found

### ISSUE THREAD

**Issue by ATLowther** [rune-js/server#363]
I can't get the project to build in docker:

`sh: 1: rimraf: not found`

If I remove the rimraf call and move the build script to just be "babel ./src --out-dir dist --extensions \".ts,.tsx,.js\" --source-maps" then it gives a `babel: not found` error.

I'm not sure if the build isn't installing dev dependencies or if it isn't sure how to reference them or what.

I will look more into it later, I am posting it here in case somebody else runs into the issue or knows the solution.

**Comment by Jameskmonger** [comment]
@ATLowther  can you please confirm that the environment variable `NODE_ENV` is not set to `production`?

If it is, `npm` won't install dev dependencies.
