### ISSUE TITLE
Client & Other Questions

### ISSUE THREAD

**Issue by misterhat** [rune-js/server#7]
Any plans on supporting https://github.com/reinismu/runescape-web-client-377/? And do y'all have an IRC channel or Discord? I'm working on a similar project but for a much earlier revision :P. Looks like we took some similar approaches, especially with cache management.

**Comment by TheBlackParade** [comment]
@misterhat Wow, I had no idea that was a thing, that's pretty awesome. As far as I know as long as it follows the same protocol and everything, this should support that client. I'm basing it off of just a regular old 377 client. Suppose I could make up a Discord.
